[application]

# App (Project) Name
name = "vortex-app"

[web.app]
base_path = "/vortex-app"
# HTML title tag content
title = "vortex-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
